#!/usr/bin/env bash
# Renders all SKILL.md bodies into a single portable AGENTS.md for non-CC agents.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/AGENTS.md"

# Strip YAML frontmatter (first --- ... --- block) from a file.
strip_fm() { awk 'BEGIN{f=0;done=0} NR==1&&$0=="---"{f=1;next} f&&!done&&$0=="---"{done=1;next} f&&!done{next} {print}' "$1"; }

{
  echo "<!-- GENERATED by scripts/build-agents-md.sh from skills/*/SKILL.md — DO NOT EDIT. Run the script to regenerate. -->"
  echo
  echo "# QaaS Platform Development — Agent Guide"
  echo
  echo "Portable bundle of the qaas-platform-dev plugin's skills, for AI agents"
  echo "other than Claude Code (Cursor, Copilot, Codex, Gemini). Source of truth is"
  echo "\`skills/*/SKILL.md\`; regenerate with \`scripts/build-agents-md.sh\`."
  echo
  # Overview first, then the rest in stable alphabetical order.
  order=("qaas-platform-overview" "add-framework-hook" "extend-framework-core" "release-and-mirror" "find-qaas-knowledge")
  for name in "${order[@]}"; do
    f="$ROOT/skills/$name/SKILL.md"
    [ -f "$f" ] || continue
    echo "---"
    echo
    strip_fm "$f"
    echo
  done
} > "$OUT"

echo "build-agents-md: wrote $OUT"
